// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: airline.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const getAvailableTravelCredits = `-- name: GetAvailableTravelCredits :many
SELECT id, customer_id, original_amount, remaining_amount, currency, status, expires_at, created_at
FROM travel_credits
WHERE customer_id = $1
  AND currency = $2
  AND remaining_amount > 0
  AND expires_at > NOW()
  AND status IN ('AVAILABLE', 'PARTIALLY_USED')
ORDER BY expires_at, created_at
`

type GetAvailableTravelCreditsParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	Currency   string    `json:"currency"`
}

func (q *Queries) GetAvailableTravelCredits(ctx context.Context, arg GetAvailableTravelCreditsParams) ([]TravelCredit, error) {
	rows, err := q.db.Query(ctx, getAvailableTravelCredits, arg.CustomerID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TravelCredit
	for rows.Next() {
		var i TravelCredit
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.OriginalAmount,
			&i.RemainingAmount,
			&i.Currency,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, first_name, last_name, email, phone, created_at, updated_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlightByID = `-- name: GetFlightByID :one
SELECT id, flight_number, origin_airport, destination_airport, departure_at, arrival_at,
       status, capacity, created_at, updated_at
FROM flights
WHERE id = $1
`

func (q *Queries) GetFlightByID(ctx context.Context, id uuid.UUID) (Flight, error) {
	row := q.db.QueryRow(ctx, getFlightByID, id)
	var i Flight
	err := row.Scan(
		&i.ID,
		&i.FlightNumber,
		&i.OriginAirport,
		&i.DestinationAirport,
		&i.DepartureAt,
		&i.ArrivalAt,
		&i.Status,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlightChangesBySegment = `-- name: GetFlightChangesBySegment :many
SELECT id, reservation_segment_id, old_flight_id, new_flight_id,
       old_fare_class_id, new_fare_class_id, fare_difference, change_fee,
       travel_credit_used, currency, created_at
FROM flight_changes
WHERE reservation_segment_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetFlightChangesBySegment(ctx context.Context, reservationSegmentID uuid.UUID) ([]FlightChange, error) {
	rows, err := q.db.Query(ctx, getFlightChangesBySegment, reservationSegmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightChange
	for rows.Next() {
		var i FlightChange
		if err := rows.Scan(
			&i.ID,
			&i.ReservationSegmentID,
			&i.OldFlightID,
			&i.NewFlightID,
			&i.OldFareClassID,
			&i.NewFareClassID,
			&i.FareDifference,
			&i.ChangeFee,
			&i.TravelCreditUsed,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPassengersByReservation = `-- name: GetPassengersByReservation :many
SELECT p.id, p.first_name, p.last_name, p.document_number, p.created_at
FROM passengers p
JOIN reservation_passengers rp ON rp.passenger_id = p.id
WHERE rp.reservation_id = $1
ORDER BY p.id
`

func (q *Queries) GetPassengersByReservation(ctx context.Context, reservationID uuid.UUID) ([]Passenger, error) {
	rows, err := q.db.Query(ctx, getPassengersByReservation, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passenger
	for rows.Next() {
		var i Passenger
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DocumentNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservationByBookingReference = `-- name: GetReservationByBookingReference :one
SELECT id, booking_reference, customer_id, status, total_amount, currency, created_at, updated_at
FROM reservations
WHERE booking_reference = $1
`

func (q *Queries) GetReservationByBookingReference(ctx context.Context, bookingReference string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByBookingReference, bookingReference)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BookingReference,
		&i.CustomerID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationCustomer = `-- name: GetReservationCustomer :one
SELECT c.id, c.first_name, c.last_name, c.email, c.phone, c.created_at, c.updated_at
FROM customers c
JOIN reservations r ON r.customer_id = c.id
WHERE r.id = $1
`

func (q *Queries) GetReservationCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getReservationCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSegmentByID = `-- name: GetSegmentByID :one
SELECT id, reservation_id, flight_id, fare_class_id, status, price_paid, currency, created_at, updated_at
FROM reservation_segments
WHERE id = $1
`

func (q *Queries) GetSegmentByID(ctx context.Context, id uuid.UUID) (ReservationSegment, error) {
	row := q.db.QueryRow(ctx, getSegmentByID, id)
	var i ReservationSegment
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.FlightID,
		&i.FareClassID,
		&i.Status,
		&i.PricePaid,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSegmentDetailsByReservation = `-- name: GetSegmentDetailsByReservation :many
SELECT
    rs.id AS segment_id, rs.reservation_id AS segment_reservation_id,
    rs.flight_id AS segment_flight_id, rs.fare_class_id AS segment_fare_class_id,
    rs.status AS segment_status, rs.price_paid AS segment_price_paid,
    rs.currency AS segment_currency, rs.created_at AS segment_created_at,
    rs.updated_at AS segment_updated_at,
    f.id AS flight_id, f.flight_number, f.origin_airport, f.destination_airport,
    f.departure_at, f.arrival_at, f.status AS flight_status, f.capacity,
    f.created_at AS flight_created_at, f.updated_at AS flight_updated_at,
    fc.id AS fare_class_id, fc.code, fc.name, fc.change_allowed,
    fc.cancellation_allowed, fc.change_fee, fc.cancellation_fee,
    fc.created_at AS fare_class_created_at
FROM reservation_segments rs
JOIN flights f ON f.id = rs.flight_id
JOIN fare_classes fc ON fc.id = rs.fare_class_id
WHERE rs.reservation_id = $1
ORDER BY rs.id
`

type GetSegmentDetailsByReservationRow struct {
	SegmentID            uuid.UUID          `json:"segment_id"`
	SegmentReservationID uuid.UUID          `json:"segment_reservation_id"`
	SegmentFlightID      uuid.UUID          `json:"segment_flight_id"`
	SegmentFareClassID   uuid.UUID          `json:"segment_fare_class_id"`
	SegmentStatus        SegmentStatus      `json:"segment_status"`
	SegmentPricePaid     decimal.Decimal    `json:"segment_price_paid"`
	SegmentCurrency      string             `json:"segment_currency"`
	SegmentCreatedAt     pgtype.Timestamptz `json:"segment_created_at"`
	SegmentUpdatedAt     pgtype.Timestamptz `json:"segment_updated_at"`
	FlightID             uuid.UUID          `json:"flight_id"`
	FlightNumber         string             `json:"flight_number"`
	OriginAirport        string             `json:"origin_airport"`
	DestinationAirport   string             `json:"destination_airport"`
	DepartureAt          pgtype.Timestamptz `json:"departure_at"`
	ArrivalAt            pgtype.Timestamptz `json:"arrival_at"`
	FlightStatus         FlightStatus       `json:"flight_status"`
	Capacity             int32              `json:"capacity"`
	FlightCreatedAt      pgtype.Timestamptz `json:"flight_created_at"`
	FlightUpdatedAt      pgtype.Timestamptz `json:"flight_updated_at"`
	FareClassID          uuid.UUID          `json:"fare_class_id"`
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	ChangeAllowed        bool               `json:"change_allowed"`
	CancellationAllowed  bool               `json:"cancellation_allowed"`
	ChangeFee            decimal.Decimal    `json:"change_fee"`
	CancellationFee      decimal.Decimal    `json:"cancellation_fee"`
	FareClassCreatedAt   pgtype.Timestamptz `json:"fare_class_created_at"`
}

func (q *Queries) GetSegmentDetailsByReservation(ctx context.Context, reservationID uuid.UUID) ([]GetSegmentDetailsByReservationRow, error) {
	rows, err := q.db.Query(ctx, getSegmentDetailsByReservation, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSegmentDetailsByReservationRow
	for rows.Next() {
		var i GetSegmentDetailsByReservationRow
		if err := rows.Scan(
			&i.SegmentID,
			&i.SegmentReservationID,
			&i.SegmentFlightID,
			&i.SegmentFareClassID,
			&i.SegmentStatus,
			&i.SegmentPricePaid,
			&i.SegmentCurrency,
			&i.SegmentCreatedAt,
			&i.SegmentUpdatedAt,
			&i.FlightID,
			&i.FlightNumber,
			&i.OriginAirport,
			&i.DestinationAirport,
			&i.DepartureAt,
			&i.ArrivalAt,
			&i.FlightStatus,
			&i.Capacity,
			&i.FlightCreatedAt,
			&i.FlightUpdatedAt,
			&i.FareClassID,
			&i.Code,
			&i.Name,
			&i.ChangeAllowed,
			&i.CancellationAllowed,
			&i.ChangeFee,
			&i.CancellationFee,
			&i.FareClassCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAvailableFlights = `-- name: SearchAvailableFlights :many
SELECT
    f.id AS flight_id, f.flight_number, f.origin_airport, f.destination_airport,
    f.departure_at, f.arrival_at, f.status AS flight_status, f.capacity,
    f.created_at AS flight_created_at, f.updated_at AS flight_updated_at,
    ff.id AS flight_fare_id, ff.flight_id AS flight_fare_flight_id,
    ff.fare_class_id AS flight_fare_class_id, ff.price, ff.currency AS fare_currency,
    ff.available_seats, fc.id AS fare_class_id, fc.code, fc.name,
    fc.change_allowed, fc.cancellation_allowed, fc.change_fee,
    fc.cancellation_fee, fc.created_at AS fare_class_created_at
FROM flights f
JOIN flight_fares ff ON ff.flight_id = f.id
JOIN fare_classes fc ON fc.id = ff.fare_class_id
WHERE f.origin_airport = $1
  AND f.destination_airport = $2
  AND f.departure_at >= $3
  AND f.departure_at <= $4
  AND f.status = 'SCHEDULED'
  AND ff.available_seats >= $5
ORDER BY f.departure_at, ff.price
`

type SearchAvailableFlightsParams struct {
	Origin         string             `json:"origin"`
	Destination    string             `json:"destination"`
	DepartureFrom  pgtype.Timestamptz `json:"departure_from"`
	DepartureTo    pgtype.Timestamptz `json:"departure_to"`
	PassengerCount int32              `json:"passenger_count"`
}

type SearchAvailableFlightsRow struct {
	FlightID            uuid.UUID          `json:"flight_id"`
	FlightNumber        string             `json:"flight_number"`
	OriginAirport       string             `json:"origin_airport"`
	DestinationAirport  string             `json:"destination_airport"`
	DepartureAt         pgtype.Timestamptz `json:"departure_at"`
	ArrivalAt           pgtype.Timestamptz `json:"arrival_at"`
	FlightStatus        FlightStatus       `json:"flight_status"`
	Capacity            int32              `json:"capacity"`
	FlightCreatedAt     pgtype.Timestamptz `json:"flight_created_at"`
	FlightUpdatedAt     pgtype.Timestamptz `json:"flight_updated_at"`
	FlightFareID        uuid.UUID          `json:"flight_fare_id"`
	FlightFareFlightID  uuid.UUID          `json:"flight_fare_flight_id"`
	FlightFareClassID   uuid.UUID          `json:"flight_fare_class_id"`
	Price               decimal.Decimal    `json:"price"`
	FareCurrency        string             `json:"fare_currency"`
	AvailableSeats      int32              `json:"available_seats"`
	FareClassID         uuid.UUID          `json:"fare_class_id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	ChangeAllowed       bool               `json:"change_allowed"`
	CancellationAllowed bool               `json:"cancellation_allowed"`
	ChangeFee           decimal.Decimal    `json:"change_fee"`
	CancellationFee     decimal.Decimal    `json:"cancellation_fee"`
	FareClassCreatedAt  pgtype.Timestamptz `json:"fare_class_created_at"`
}

func (q *Queries) SearchAvailableFlights(ctx context.Context, arg SearchAvailableFlightsParams) ([]SearchAvailableFlightsRow, error) {
	rows, err := q.db.Query(ctx, searchAvailableFlights,
		arg.Origin,
		arg.Destination,
		arg.DepartureFrom,
		arg.DepartureTo,
		arg.PassengerCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAvailableFlightsRow
	for rows.Next() {
		var i SearchAvailableFlightsRow
		if err := rows.Scan(
			&i.FlightID,
			&i.FlightNumber,
			&i.OriginAirport,
			&i.DestinationAirport,
			&i.DepartureAt,
			&i.ArrivalAt,
			&i.FlightStatus,
			&i.Capacity,
			&i.FlightCreatedAt,
			&i.FlightUpdatedAt,
			&i.FlightFareID,
			&i.FlightFareFlightID,
			&i.FlightFareClassID,
			&i.Price,
			&i.FareCurrency,
			&i.AvailableSeats,
			&i.FareClassID,
			&i.Code,
			&i.Name,
			&i.ChangeAllowed,
			&i.CancellationAllowed,
			&i.ChangeFee,
			&i.CancellationFee,
			&i.FareClassCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
