// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: airline.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const consumeTravelCredit = `-- name: ConsumeTravelCredit :exec
UPDATE travel_credits
SET remaining_amount = remaining_amount - $2,
    status = CASE WHEN remaining_amount - $2 = 0 THEN 'USED' ELSE 'PARTIALLY_USED' END
WHERE id = $1 AND remaining_amount >= $2
`

type ConsumeTravelCreditParams struct {
	ID              uuid.UUID       `json:"id"`
	RemainingAmount decimal.Decimal `json:"remaining_amount"`
}

func (q *Queries) ConsumeTravelCredit(ctx context.Context, arg ConsumeTravelCreditParams) error {
	_, err := q.db.Exec(ctx, consumeTravelCredit, arg.ID, arg.RemainingAmount)
	return err
}

const createFlightChange = `-- name: CreateFlightChange :one
INSERT INTO flight_changes (
    id, reservation_segment_id, old_flight_id, new_flight_id,
    old_fare_class_id, new_fare_class_id, fare_difference, change_fee,
    travel_credit_used, currency, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
RETURNING id, reservation_segment_id, old_flight_id, new_flight_id,
          old_fare_class_id, new_fare_class_id, fare_difference, change_fee,
          travel_credit_used, currency, created_at
`

type CreateFlightChangeParams struct {
	ID                   uuid.UUID       `json:"id"`
	ReservationSegmentID uuid.UUID       `json:"reservation_segment_id"`
	OldFlightID          uuid.UUID       `json:"old_flight_id"`
	NewFlightID          uuid.UUID       `json:"new_flight_id"`
	OldFareClassID       uuid.UUID       `json:"old_fare_class_id"`
	NewFareClassID       uuid.UUID       `json:"new_fare_class_id"`
	FareDifference       decimal.Decimal `json:"fare_difference"`
	ChangeFee            decimal.Decimal `json:"change_fee"`
	TravelCreditUsed     decimal.Decimal `json:"travel_credit_used"`
	Currency             string          `json:"currency"`
}

func (q *Queries) CreateFlightChange(ctx context.Context, arg CreateFlightChangeParams) (FlightChange, error) {
	row := q.db.QueryRow(ctx, createFlightChange,
		arg.ID,
		arg.ReservationSegmentID,
		arg.OldFlightID,
		arg.NewFlightID,
		arg.OldFareClassID,
		arg.NewFareClassID,
		arg.FareDifference,
		arg.ChangeFee,
		arg.TravelCreditUsed,
		arg.Currency,
	)
	var i FlightChange
	err := row.Scan(
		&i.ID,
		&i.ReservationSegmentID,
		&i.OldFlightID,
		&i.NewFlightID,
		&i.OldFareClassID,
		&i.NewFareClassID,
		&i.FareDifference,
		&i.ChangeFee,
		&i.TravelCreditUsed,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const decrementFlightFareSeats = `-- name: DecrementFlightFareSeats :exec
UPDATE flight_fares
SET available_seats = available_seats - $1
WHERE flight_id = $2 AND fare_class_id = $3
  AND available_seats >= $1
`

type DecrementFlightFareSeatsParams struct {
	PassengerCount int32     `json:"passenger_count"`
	FlightID       uuid.UUID `json:"flight_id"`
	FareClassID    uuid.UUID `json:"fare_class_id"`
}

func (q *Queries) DecrementFlightFareSeats(ctx context.Context, arg DecrementFlightFareSeatsParams) error {
	_, err := q.db.Exec(ctx, decrementFlightFareSeats, arg.PassengerCount, arg.FlightID, arg.FareClassID)
	return err
}

const getAvailableTravelCredits = `-- name: GetAvailableTravelCredits :many
SELECT id, customer_id, original_amount, remaining_amount, currency, status, expires_at, created_at
FROM travel_credits
WHERE customer_id = $1
  AND currency = $2
  AND remaining_amount > 0
  AND expires_at > NOW()
  AND status IN ('AVAILABLE', 'PARTIALLY_USED')
ORDER BY expires_at, created_at
`

type GetAvailableTravelCreditsParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	Currency   string    `json:"currency"`
}

func (q *Queries) GetAvailableTravelCredits(ctx context.Context, arg GetAvailableTravelCreditsParams) ([]TravelCredit, error) {
	rows, err := q.db.Query(ctx, getAvailableTravelCredits, arg.CustomerID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TravelCredit
	for rows.Next() {
		var i TravelCredit
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.OriginalAmount,
			&i.RemainingAmount,
			&i.Currency,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, first_name, last_name, email, phone, created_at, updated_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlightByID = `-- name: GetFlightByID :one
SELECT id, flight_number, origin_airport, destination_airport, departure_at, arrival_at,
       status, capacity, created_at, updated_at
FROM flights
WHERE id = $1
`

func (q *Queries) GetFlightByID(ctx context.Context, id uuid.UUID) (Flight, error) {
	row := q.db.QueryRow(ctx, getFlightByID, id)
	var i Flight
	err := row.Scan(
		&i.ID,
		&i.FlightNumber,
		&i.OriginAirport,
		&i.DestinationAirport,
		&i.DepartureAt,
		&i.ArrivalAt,
		&i.Status,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlightChangesBySegment = `-- name: GetFlightChangesBySegment :many
SELECT id, reservation_segment_id, old_flight_id, new_flight_id,
       old_fare_class_id, new_fare_class_id, fare_difference, change_fee,
       travel_credit_used, currency, created_at
FROM flight_changes
WHERE reservation_segment_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetFlightChangesBySegment(ctx context.Context, reservationSegmentID uuid.UUID) ([]FlightChange, error) {
	rows, err := q.db.Query(ctx, getFlightChangesBySegment, reservationSegmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightChange
	for rows.Next() {
		var i FlightChange
		if err := rows.Scan(
			&i.ID,
			&i.ReservationSegmentID,
			&i.OldFlightID,
			&i.NewFlightID,
			&i.OldFareClassID,
			&i.NewFareClassID,
			&i.FareDifference,
			&i.ChangeFee,
			&i.TravelCreditUsed,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPassengersByReservation = `-- name: GetPassengersByReservation :many
SELECT p.id, p.first_name, p.last_name, p.document_number, p.created_at
FROM passengers p
JOIN reservation_passengers rp ON rp.passenger_id = p.id
WHERE rp.reservation_id = $1
ORDER BY p.id
`

func (q *Queries) GetPassengersByReservation(ctx context.Context, reservationID uuid.UUID) ([]Passenger, error) {
	rows, err := q.db.Query(ctx, getPassengersByReservation, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passenger
	for rows.Next() {
		var i Passenger
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DocumentNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRebookingResult = `-- name: GetRebookingResult :one
SELECT rs.id AS segment_id, rs.reservation_id, rs.flight_id, rs.fare_class_id,
       rs.status AS segment_status, rs.price_paid, rs.currency,
       r.booking_reference
FROM reservation_segments rs
JOIN reservations r ON r.id = rs.reservation_id
WHERE rs.id = $1
`

type GetRebookingResultRow struct {
	SegmentID        uuid.UUID       `json:"segment_id"`
	ReservationID    uuid.UUID       `json:"reservation_id"`
	FlightID         uuid.UUID       `json:"flight_id"`
	FareClassID      uuid.UUID       `json:"fare_class_id"`
	SegmentStatus    SegmentStatus   `json:"segment_status"`
	PricePaid        decimal.Decimal `json:"price_paid"`
	Currency         string          `json:"currency"`
	BookingReference string          `json:"booking_reference"`
}

func (q *Queries) GetRebookingResult(ctx context.Context, id uuid.UUID) (GetRebookingResultRow, error) {
	row := q.db.QueryRow(ctx, getRebookingResult, id)
	var i GetRebookingResultRow
	err := row.Scan(
		&i.SegmentID,
		&i.ReservationID,
		&i.FlightID,
		&i.FareClassID,
		&i.SegmentStatus,
		&i.PricePaid,
		&i.Currency,
		&i.BookingReference,
	)
	return i, err
}

const getRebookingSegmentForUpdate = `-- name: GetRebookingSegmentForUpdate :one
SELECT rs.id AS segment_id, rs.reservation_id, rs.flight_id AS old_flight_id,
       rs.fare_class_id AS old_fare_class_id, rs.status AS segment_status,
       rs.price_paid, rs.currency AS segment_currency,
       r.customer_id, r.status AS reservation_status,
        old_f.status AS old_flight_status, old_f.origin_airport, old_f.destination_airport,
        old_f.departure_at AS old_departure_at,
        (SELECT COUNT(*) FROM reservation_passengers rp WHERE rp.reservation_id = rs.reservation_id) AS passenger_count,
        old_fc.change_allowed AS old_change_allowed, old_fc.change_fee
FROM reservation_segments rs
JOIN reservations r ON r.id = rs.reservation_id
JOIN flights old_f ON old_f.id = rs.flight_id
JOIN fare_classes old_fc ON old_fc.id = rs.fare_class_id
WHERE rs.id = $1
FOR UPDATE OF rs, r
`

type GetRebookingSegmentForUpdateRow struct {
	SegmentID          uuid.UUID          `json:"segment_id"`
	ReservationID      uuid.UUID          `json:"reservation_id"`
	OldFlightID        uuid.UUID          `json:"old_flight_id"`
	OldFareClassID     uuid.UUID          `json:"old_fare_class_id"`
	SegmentStatus      SegmentStatus      `json:"segment_status"`
	PricePaid          decimal.Decimal    `json:"price_paid"`
	SegmentCurrency    string             `json:"segment_currency"`
	CustomerID         uuid.UUID          `json:"customer_id"`
	ReservationStatus  ReservationStatus  `json:"reservation_status"`
	OldFlightStatus    FlightStatus       `json:"old_flight_status"`
	OriginAirport      string             `json:"origin_airport"`
	DestinationAirport string             `json:"destination_airport"`
	OldDepartureAt     pgtype.Timestamptz `json:"old_departure_at"`
	PassengerCount     int64              `json:"passenger_count"`
	OldChangeAllowed   bool               `json:"old_change_allowed"`
	ChangeFee          decimal.Decimal    `json:"change_fee"`
}

func (q *Queries) GetRebookingSegmentForUpdate(ctx context.Context, id uuid.UUID) (GetRebookingSegmentForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRebookingSegmentForUpdate, id)
	var i GetRebookingSegmentForUpdateRow
	err := row.Scan(
		&i.SegmentID,
		&i.ReservationID,
		&i.OldFlightID,
		&i.OldFareClassID,
		&i.SegmentStatus,
		&i.PricePaid,
		&i.SegmentCurrency,
		&i.CustomerID,
		&i.ReservationStatus,
		&i.OldFlightStatus,
		&i.OriginAirport,
		&i.DestinationAirport,
		&i.OldDepartureAt,
		&i.PassengerCount,
		&i.OldChangeAllowed,
		&i.ChangeFee,
	)
	return i, err
}

const getRebookingTargetForUpdate = `-- name: GetRebookingTargetForUpdate :one
SELECT f.id AS flight_id, f.status AS flight_status,
       f.origin_airport, f.destination_airport, f.departure_at,
       ff.id AS flight_fare_id, ff.fare_class_id, ff.price,
       ff.currency, ff.available_seats,
       fc.change_allowed, fc.change_fee
FROM flights f
JOIN flight_fares ff ON ff.flight_id = f.id
JOIN fare_classes fc ON fc.id = ff.fare_class_id
WHERE f.id = $1 AND ff.fare_class_id = $2
FOR UPDATE OF f, ff
`

type GetRebookingTargetForUpdateParams struct {
	ID          uuid.UUID `json:"id"`
	FareClassID uuid.UUID `json:"fare_class_id"`
}

type GetRebookingTargetForUpdateRow struct {
	FlightID           uuid.UUID          `json:"flight_id"`
	FlightStatus       FlightStatus       `json:"flight_status"`
	OriginAirport      string             `json:"origin_airport"`
	DestinationAirport string             `json:"destination_airport"`
	DepartureAt        pgtype.Timestamptz `json:"departure_at"`
	FlightFareID       uuid.UUID          `json:"flight_fare_id"`
	FareClassID        uuid.UUID          `json:"fare_class_id"`
	Price              decimal.Decimal    `json:"price"`
	Currency           string             `json:"currency"`
	AvailableSeats     int32              `json:"available_seats"`
	ChangeAllowed      bool               `json:"change_allowed"`
	ChangeFee          decimal.Decimal    `json:"change_fee"`
}

func (q *Queries) GetRebookingTargetForUpdate(ctx context.Context, arg GetRebookingTargetForUpdateParams) (GetRebookingTargetForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRebookingTargetForUpdate, arg.ID, arg.FareClassID)
	var i GetRebookingTargetForUpdateRow
	err := row.Scan(
		&i.FlightID,
		&i.FlightStatus,
		&i.OriginAirport,
		&i.DestinationAirport,
		&i.DepartureAt,
		&i.FlightFareID,
		&i.FareClassID,
		&i.Price,
		&i.Currency,
		&i.AvailableSeats,
		&i.ChangeAllowed,
		&i.ChangeFee,
	)
	return i, err
}

const getReservationByBookingReference = `-- name: GetReservationByBookingReference :one
SELECT id, booking_reference, customer_id, status, total_amount, currency, created_at, updated_at
FROM reservations
WHERE booking_reference = $1
`

func (q *Queries) GetReservationByBookingReference(ctx context.Context, bookingReference string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByBookingReference, bookingReference)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BookingReference,
		&i.CustomerID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationCustomer = `-- name: GetReservationCustomer :one
SELECT c.id, c.first_name, c.last_name, c.email, c.phone, c.created_at, c.updated_at
FROM customers c
JOIN reservations r ON r.customer_id = c.id
WHERE r.id = $1
`

func (q *Queries) GetReservationCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getReservationCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSegmentByID = `-- name: GetSegmentByID :one
SELECT id, reservation_id, flight_id, fare_class_id, status, price_paid, currency, created_at, updated_at
FROM reservation_segments
WHERE id = $1
`

func (q *Queries) GetSegmentByID(ctx context.Context, id uuid.UUID) (ReservationSegment, error) {
	row := q.db.QueryRow(ctx, getSegmentByID, id)
	var i ReservationSegment
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.FlightID,
		&i.FareClassID,
		&i.Status,
		&i.PricePaid,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSegmentDetailsByReservation = `-- name: GetSegmentDetailsByReservation :many
SELECT
    rs.id AS segment_id, rs.reservation_id AS segment_reservation_id,
    rs.flight_id AS segment_flight_id, rs.fare_class_id AS segment_fare_class_id,
    rs.status AS segment_status, rs.price_paid AS segment_price_paid,
    rs.currency AS segment_currency, rs.created_at AS segment_created_at,
    rs.updated_at AS segment_updated_at,
    f.id AS flight_id, f.flight_number, f.origin_airport, f.destination_airport,
    f.departure_at, f.arrival_at, f.status AS flight_status, f.capacity,
    f.created_at AS flight_created_at, f.updated_at AS flight_updated_at,
    fc.id AS fare_class_id, fc.code, fc.name, fc.change_allowed,
    fc.cancellation_allowed, fc.change_fee, fc.cancellation_fee,
    fc.created_at AS fare_class_created_at
FROM reservation_segments rs
JOIN flights f ON f.id = rs.flight_id
JOIN fare_classes fc ON fc.id = rs.fare_class_id
WHERE rs.reservation_id = $1
ORDER BY rs.id
`

type GetSegmentDetailsByReservationRow struct {
	SegmentID            uuid.UUID          `json:"segment_id"`
	SegmentReservationID uuid.UUID          `json:"segment_reservation_id"`
	SegmentFlightID      uuid.UUID          `json:"segment_flight_id"`
	SegmentFareClassID   uuid.UUID          `json:"segment_fare_class_id"`
	SegmentStatus        SegmentStatus      `json:"segment_status"`
	SegmentPricePaid     decimal.Decimal    `json:"segment_price_paid"`
	SegmentCurrency      string             `json:"segment_currency"`
	SegmentCreatedAt     pgtype.Timestamptz `json:"segment_created_at"`
	SegmentUpdatedAt     pgtype.Timestamptz `json:"segment_updated_at"`
	FlightID             uuid.UUID          `json:"flight_id"`
	FlightNumber         string             `json:"flight_number"`
	OriginAirport        string             `json:"origin_airport"`
	DestinationAirport   string             `json:"destination_airport"`
	DepartureAt          pgtype.Timestamptz `json:"departure_at"`
	ArrivalAt            pgtype.Timestamptz `json:"arrival_at"`
	FlightStatus         FlightStatus       `json:"flight_status"`
	Capacity             int32              `json:"capacity"`
	FlightCreatedAt      pgtype.Timestamptz `json:"flight_created_at"`
	FlightUpdatedAt      pgtype.Timestamptz `json:"flight_updated_at"`
	FareClassID          uuid.UUID          `json:"fare_class_id"`
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	ChangeAllowed        bool               `json:"change_allowed"`
	CancellationAllowed  bool               `json:"cancellation_allowed"`
	ChangeFee            decimal.Decimal    `json:"change_fee"`
	CancellationFee      decimal.Decimal    `json:"cancellation_fee"`
	FareClassCreatedAt   pgtype.Timestamptz `json:"fare_class_created_at"`
}

func (q *Queries) GetSegmentDetailsByReservation(ctx context.Context, reservationID uuid.UUID) ([]GetSegmentDetailsByReservationRow, error) {
	rows, err := q.db.Query(ctx, getSegmentDetailsByReservation, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSegmentDetailsByReservationRow
	for rows.Next() {
		var i GetSegmentDetailsByReservationRow
		if err := rows.Scan(
			&i.SegmentID,
			&i.SegmentReservationID,
			&i.SegmentFlightID,
			&i.SegmentFareClassID,
			&i.SegmentStatus,
			&i.SegmentPricePaid,
			&i.SegmentCurrency,
			&i.SegmentCreatedAt,
			&i.SegmentUpdatedAt,
			&i.FlightID,
			&i.FlightNumber,
			&i.OriginAirport,
			&i.DestinationAirport,
			&i.DepartureAt,
			&i.ArrivalAt,
			&i.FlightStatus,
			&i.Capacity,
			&i.FlightCreatedAt,
			&i.FlightUpdatedAt,
			&i.FareClassID,
			&i.Code,
			&i.Name,
			&i.ChangeAllowed,
			&i.CancellationAllowed,
			&i.ChangeFee,
			&i.CancellationFee,
			&i.FareClassCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTravelCreditForUpdate = `-- name: GetTravelCreditForUpdate :one
SELECT id, customer_id, original_amount, remaining_amount, currency, status, expires_at, created_at
FROM travel_credits
WHERE id = $1 AND customer_id = $2
FOR UPDATE
`

type GetTravelCreditForUpdateParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) GetTravelCreditForUpdate(ctx context.Context, arg GetTravelCreditForUpdateParams) (TravelCredit, error) {
	row := q.db.QueryRow(ctx, getTravelCreditForUpdate, arg.ID, arg.CustomerID)
	var i TravelCredit
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OriginalAmount,
		&i.RemainingAmount,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementFlightFareSeats = `-- name: IncrementFlightFareSeats :exec
UPDATE flight_fares
SET available_seats = available_seats + $1
WHERE flight_id = $2 AND fare_class_id = $3
`

type IncrementFlightFareSeatsParams struct {
	PassengerCount int32     `json:"passenger_count"`
	FlightID       uuid.UUID `json:"flight_id"`
	FareClassID    uuid.UUID `json:"fare_class_id"`
}

func (q *Queries) IncrementFlightFareSeats(ctx context.Context, arg IncrementFlightFareSeatsParams) error {
	_, err := q.db.Exec(ctx, incrementFlightFareSeats, arg.PassengerCount, arg.FlightID, arg.FareClassID)
	return err
}

const searchAvailableFlights = `-- name: SearchAvailableFlights :many
SELECT
    f.id AS flight_id, f.flight_number, f.origin_airport, f.destination_airport,
    f.departure_at, f.arrival_at, f.status AS flight_status, f.capacity,
    f.created_at AS flight_created_at, f.updated_at AS flight_updated_at,
    ff.id AS flight_fare_id, ff.flight_id AS flight_fare_flight_id,
    ff.fare_class_id AS flight_fare_class_id, ff.price, ff.currency AS fare_currency,
    ff.available_seats, fc.id AS fare_class_id, fc.code, fc.name,
    fc.change_allowed, fc.cancellation_allowed, fc.change_fee,
    fc.cancellation_fee, fc.created_at AS fare_class_created_at
FROM flights f
JOIN flight_fares ff ON ff.flight_id = f.id
JOIN fare_classes fc ON fc.id = ff.fare_class_id
WHERE f.origin_airport = $1
  AND f.destination_airport = $2
  AND f.departure_at >= $3
  AND f.departure_at <= $4
  AND f.status = 'SCHEDULED'
  AND ff.available_seats >= $5
ORDER BY f.departure_at, ff.price
`

type SearchAvailableFlightsParams struct {
	Origin         string             `json:"origin"`
	Destination    string             `json:"destination"`
	DepartureFrom  pgtype.Timestamptz `json:"departure_from"`
	DepartureTo    pgtype.Timestamptz `json:"departure_to"`
	PassengerCount int32              `json:"passenger_count"`
}

type SearchAvailableFlightsRow struct {
	FlightID            uuid.UUID          `json:"flight_id"`
	FlightNumber        string             `json:"flight_number"`
	OriginAirport       string             `json:"origin_airport"`
	DestinationAirport  string             `json:"destination_airport"`
	DepartureAt         pgtype.Timestamptz `json:"departure_at"`
	ArrivalAt           pgtype.Timestamptz `json:"arrival_at"`
	FlightStatus        FlightStatus       `json:"flight_status"`
	Capacity            int32              `json:"capacity"`
	FlightCreatedAt     pgtype.Timestamptz `json:"flight_created_at"`
	FlightUpdatedAt     pgtype.Timestamptz `json:"flight_updated_at"`
	FlightFareID        uuid.UUID          `json:"flight_fare_id"`
	FlightFareFlightID  uuid.UUID          `json:"flight_fare_flight_id"`
	FlightFareClassID   uuid.UUID          `json:"flight_fare_class_id"`
	Price               decimal.Decimal    `json:"price"`
	FareCurrency        string             `json:"fare_currency"`
	AvailableSeats      int32              `json:"available_seats"`
	FareClassID         uuid.UUID          `json:"fare_class_id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	ChangeAllowed       bool               `json:"change_allowed"`
	CancellationAllowed bool               `json:"cancellation_allowed"`
	ChangeFee           decimal.Decimal    `json:"change_fee"`
	CancellationFee     decimal.Decimal    `json:"cancellation_fee"`
	FareClassCreatedAt  pgtype.Timestamptz `json:"fare_class_created_at"`
}

func (q *Queries) SearchAvailableFlights(ctx context.Context, arg SearchAvailableFlightsParams) ([]SearchAvailableFlightsRow, error) {
	rows, err := q.db.Query(ctx, searchAvailableFlights,
		arg.Origin,
		arg.Destination,
		arg.DepartureFrom,
		arg.DepartureTo,
		arg.PassengerCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAvailableFlightsRow
	for rows.Next() {
		var i SearchAvailableFlightsRow
		if err := rows.Scan(
			&i.FlightID,
			&i.FlightNumber,
			&i.OriginAirport,
			&i.DestinationAirport,
			&i.DepartureAt,
			&i.ArrivalAt,
			&i.FlightStatus,
			&i.Capacity,
			&i.FlightCreatedAt,
			&i.FlightUpdatedAt,
			&i.FlightFareID,
			&i.FlightFareFlightID,
			&i.FlightFareClassID,
			&i.Price,
			&i.FareCurrency,
			&i.AvailableSeats,
			&i.FareClassID,
			&i.Code,
			&i.Name,
			&i.ChangeAllowed,
			&i.CancellationAllowed,
			&i.ChangeFee,
			&i.CancellationFee,
			&i.FareClassCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationSegment = `-- name: UpdateReservationSegment :exec
UPDATE reservation_segments
SET flight_id = $2, fare_class_id = $3, price_paid = $4,
    status = 'CHANGED', currency = $5, updated_at = NOW()
WHERE id = $1
`

type UpdateReservationSegmentParams struct {
	ID          uuid.UUID       `json:"id"`
	FlightID    uuid.UUID       `json:"flight_id"`
	FareClassID uuid.UUID       `json:"fare_class_id"`
	PricePaid   decimal.Decimal `json:"price_paid"`
	Currency    string          `json:"currency"`
}

func (q *Queries) UpdateReservationSegment(ctx context.Context, arg UpdateReservationSegmentParams) error {
	_, err := q.db.Exec(ctx, updateReservationSegment,
		arg.ID,
		arg.FlightID,
		arg.FareClassID,
		arg.PricePaid,
		arg.Currency,
	)
	return err
}

const updateReservationTotal = `-- name: UpdateReservationTotal :exec
UPDATE reservations
SET total_amount = total_amount + $2, updated_at = NOW()
WHERE id = $1
`

type UpdateReservationTotalParams struct {
	ID          uuid.UUID       `json:"id"`
	TotalAmount decimal.Decimal `json:"total_amount"`
}

func (q *Queries) UpdateReservationTotal(ctx context.Context, arg UpdateReservationTotalParams) error {
	_, err := q.db.Exec(ctx, updateReservationTotal, arg.ID, arg.TotalAmount)
	return err
}
