// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

type FlightStatus string

const (
	FlightStatusSCHEDULED FlightStatus = "SCHEDULED"
	FlightStatusDELAYED   FlightStatus = "DELAYED"
	FlightStatusCANCELLED FlightStatus = "CANCELLED"
	FlightStatusBOARDING  FlightStatus = "BOARDING"
	FlightStatusDEPARTED  FlightStatus = "DEPARTED"
	FlightStatusCOMPLETED FlightStatus = "COMPLETED"
)

func (e *FlightStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlightStatus(s)
	case string:
		*e = FlightStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlightStatus: %T", src)
	}
	return nil
}

type NullFlightStatus struct {
	FlightStatus FlightStatus `json:"flight_status"`
	Valid        bool         `json:"valid"` // Valid is true if FlightStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlightStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlightStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlightStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlightStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlightStatus), nil
}

type ReservationStatus string

const (
	ReservationStatusCONFIRMED ReservationStatus = "CONFIRMED"
	ReservationStatusCANCELLED ReservationStatus = "CANCELLED"
	ReservationStatusCOMPLETED ReservationStatus = "COMPLETED"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus `json:"reservation_status"`
	Valid             bool              `json:"valid"` // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

type SegmentStatus string

const (
	SegmentStatusCONFIRMED SegmentStatus = "CONFIRMED"
	SegmentStatusCHANGED   SegmentStatus = "CHANGED"
	SegmentStatusCANCELLED SegmentStatus = "CANCELLED"
	SegmentStatusFLOWN     SegmentStatus = "FLOWN"
)

func (e *SegmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SegmentStatus(s)
	case string:
		*e = SegmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SegmentStatus: %T", src)
	}
	return nil
}

type NullSegmentStatus struct {
	SegmentStatus SegmentStatus `json:"segment_status"`
	Valid         bool          `json:"valid"` // Valid is true if SegmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSegmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SegmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SegmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSegmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SegmentStatus), nil
}

type TravelCreditStatus string

const (
	TravelCreditStatusAVAILABLE     TravelCreditStatus = "AVAILABLE"
	TravelCreditStatusPARTIALLYUSED TravelCreditStatus = "PARTIALLY_USED"
	TravelCreditStatusUSED          TravelCreditStatus = "USED"
	TravelCreditStatusEXPIRED       TravelCreditStatus = "EXPIRED"
)

func (e *TravelCreditStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TravelCreditStatus(s)
	case string:
		*e = TravelCreditStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TravelCreditStatus: %T", src)
	}
	return nil
}

type NullTravelCreditStatus struct {
	TravelCreditStatus TravelCreditStatus `json:"travel_credit_status"`
	Valid              bool               `json:"valid"` // Valid is true if TravelCreditStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTravelCreditStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TravelCreditStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TravelCreditStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTravelCreditStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TravelCreditStatus), nil
}

type Customer struct {
	ID        uuid.UUID          `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type FareClass struct {
	ID                  uuid.UUID          `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	ChangeAllowed       bool               `json:"change_allowed"`
	CancellationAllowed bool               `json:"cancellation_allowed"`
	ChangeFee           decimal.Decimal    `json:"change_fee"`
	CancellationFee     decimal.Decimal    `json:"cancellation_fee"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Flight struct {
	ID                 uuid.UUID          `json:"id"`
	FlightNumber       string             `json:"flight_number"`
	OriginAirport      string             `json:"origin_airport"`
	DestinationAirport string             `json:"destination_airport"`
	DepartureAt        pgtype.Timestamptz `json:"departure_at"`
	ArrivalAt          pgtype.Timestamptz `json:"arrival_at"`
	Status             FlightStatus       `json:"status"`
	Capacity           int32              `json:"capacity"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type FlightChange struct {
	ID                   uuid.UUID          `json:"id"`
	ReservationSegmentID uuid.UUID          `json:"reservation_segment_id"`
	OldFlightID          uuid.UUID          `json:"old_flight_id"`
	NewFlightID          uuid.UUID          `json:"new_flight_id"`
	OldFareClassID       uuid.UUID          `json:"old_fare_class_id"`
	NewFareClassID       uuid.UUID          `json:"new_fare_class_id"`
	FareDifference       decimal.Decimal    `json:"fare_difference"`
	ChangeFee            decimal.Decimal    `json:"change_fee"`
	TravelCreditUsed     decimal.Decimal    `json:"travel_credit_used"`
	Currency             string             `json:"currency"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type FlightFare struct {
	ID             uuid.UUID       `json:"id"`
	FlightID       uuid.UUID       `json:"flight_id"`
	FareClassID    uuid.UUID       `json:"fare_class_id"`
	Price          decimal.Decimal `json:"price"`
	Currency       string          `json:"currency"`
	AvailableSeats int32           `json:"available_seats"`
}

type Passenger struct {
	ID             uuid.UUID          `json:"id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	DocumentNumber string             `json:"document_number"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Reservation struct {
	ID               uuid.UUID          `json:"id"`
	BookingReference string             `json:"booking_reference"`
	CustomerID       uuid.UUID          `json:"customer_id"`
	Status           ReservationStatus  `json:"status"`
	TotalAmount      decimal.Decimal    `json:"total_amount"`
	Currency         string             `json:"currency"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ReservationPassenger struct {
	ReservationID uuid.UUID `json:"reservation_id"`
	PassengerID   uuid.UUID `json:"passenger_id"`
}

type ReservationSegment struct {
	ID            uuid.UUID          `json:"id"`
	ReservationID uuid.UUID          `json:"reservation_id"`
	FlightID      uuid.UUID          `json:"flight_id"`
	FareClassID   uuid.UUID          `json:"fare_class_id"`
	Status        SegmentStatus      `json:"status"`
	PricePaid     decimal.Decimal    `json:"price_paid"`
	Currency      string             `json:"currency"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TravelCredit struct {
	ID              uuid.UUID          `json:"id"`
	CustomerID      uuid.UUID          `json:"customer_id"`
	OriginalAmount  decimal.Decimal    `json:"original_amount"`
	RemainingAmount decimal.Decimal    `json:"remaining_amount"`
	Currency        string             `json:"currency"`
	Status          TravelCreditStatus `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
